### ISSUE TITLE
Unbreakable doesnt work on Armor pieces

### ISSUE THREAD

**Issue by Sakens** [CrimsonFluff/Unbreakables#1]
The Unbreakable enchantment doesnt work on Armor it still shows as example "Unbreaking III, Unbreakable".

**Comment by CrimsonFluff** [comment]
just tried it on diamond helmet, iron chest piece, gold leggings and chain mail boots

it works

**Comment by Sakens** [comment]
![2022-01-04_21 49 36](https://user-images.githubusercontent.com/97121216/148122293-d850e380-73aa-4607-b256-7fa3582ad7d5.png)


Well this is what is happening for me. Im only using this mod and the recommended forge version of this mod.

**Comment by CrimsonFluff** [comment]
which version 1.16.5 or 1.18.1 ??  any fancy gamemodes? gamerule changes?

**Comment by Sakens** [comment]
1.18.1 testet it with both forge version 39.0.05 and 10 as said tried it with mods and only with this one. no gamerule changes in creative and cheats enabled. gamemode is normal.

**Comment by CrimsonFluff** [comment]
can you post your `latest.log`  file.  Ive tested both forge 1.16.5 and 1.18.1, in creative, in survival, in dev, outside dev, with mods, without mods, it works fine for me, so I dont know what to suggest

**Comment by Sakens** [comment]
[latest.log](https://github.com/CrimsonFluff/Unbreakables/files/7810718/latest.log)

**Comment by CrimsonFluff** [comment]
can you please try this version: Ive simply added some debug messages into the code

https://1drv.ms/u/s!ArSGAcC04KWsyxRkhbCeClgk53nC?e=4MJ92L

Use it as you would normally. When you close minecraft please send me the `latest.log` again, as it should contain the debug messages

**Comment by Sakens** [comment]
[latest.log](https://github.com/CrimsonFluff/Unbreakables/files/7811627/latest.log)

**Comment by CrimsonFluff** [comment]
ok so the code that applies the enchantment is not being run
so this is gonna sound really dumb...but lets do this step by step

```
cheat in a diamond helmet
cheat in an anvil
cheat in the unbreakable enchanted book
give yourself 100 levels of xp, using a command
go into survival
put the helmet in the anvil
add the book into the anvil
take the enchanted helmet out the anvil
wear the helmet
```

thats what you do right?

**Comment by Sakens** [comment]
Basically yes. In creative i gave myself a diamond helmet, the book and the anvil. Then applied the enchantment and then got into survival and tested it.

**Comment by CrimsonFluff** [comment]
I have no idea then

**Comment by Sakens** [comment]
Its so weird. Im probably the only one who has this problem. I tried reinstalling minecraft and reinstalling java but nothing... maybe the debug.log will help you?

**Comment by CrimsonFluff** [comment]
you can post it, but I really dont understand whats happening?

can we just double check some stuff: im using:
Forge version: 39.0.10
Java version: 17.0.1 64bit
O/S: Windows 10

Does it work for tools? pickaxes, hoes etc?
Did you download it from curseforge?  cos thats usually the only place I post mods to

**Comment by Sakens** [comment]
[debug.log](https://github.com/CrimsonFluff/Unbreakables/files/7816996/debug.log)
I tested both forge 39.0.10 and 05
Java: 1.8.0
Windows 10 x64

I only download mods from curseforge. And it seems like now it doesnt even work for tools anymore... im so lost.

**Comment by CrimsonFluff** [comment]
Java 1.8.0 ?  you need java 17 at least for Minecraft 1.18  (use F3 debug screen in minecraft to show java version)

**Comment by Sakens** [comment]
[world.zip](https://github.com/CrimsonFluff/Unbreakables/files/7817190/world.zip)

**Comment by Sakens** [comment]
and the java version I installed is the most recent, i dont think thats the problem

**Comment by CrimsonFluff** [comment]
I just added unbreakable to a brand new item and an existing netherite item (that was in inventory when I loaded the world)

and all was ok

so im even more lost than you are....

**Comment by CrimsonFluff** [comment]
could you create a quick 1.16.5 instance in curseforge app and try that version of the mod?

**Comment by Sakens** [comment]
on 1.16.5 it doesnt work either

**Comment by CrimsonFluff** [comment]
I really dont know what to suggest - our setups seem the same, the debug is the same

can you try this version, its 1.18.1, it will print extra debug info, try it and send me the `latest.log` again please

**Comment by Sakens** [comment]
[latest.log](https://github.com/CrimsonFluff/Unbreakables/files/7817496/latest.log)

**Comment by CrimsonFluff** [comment]
some weird reason it returns `air` when you remove the item from the anvil, but it still has the correct enchantment tags attached to the `air`

which is really weird

**Comment by Sakens** [comment]
wth is going on help

**Comment by Sakens** [comment]
okay let me try something else im using the enchant command and then the give command

**Comment by Sakens** [comment]
nope doesnt work

**Comment by CrimsonFluff** [comment]
try /give @a diamond_helmet{"Unbreakable":1b}

**Comment by Sakens** [comment]
![2022-01-05_21 23 37](https://user-images.githubusercontent.com/97121216/148284049-2e9b7327-2282-47e2-9972-077f68d7f340.png)
That works ^^

**Comment by CrimsonFluff** [comment]
thats all my mod does, it removes the actual enchant and adds that tag to the item

but because the item returned is air, it wont apply the tag because it thinks the item is empty

**Comment by CrimsonFluff** [comment]
as it returns the correct enchantment, I could just check for the unbreakable enchant and apply it to the item - but it means avoiding the `empty` / `air` check - i would rather figure out why its happening

**Comment by Sakens** [comment]
OOOKAY if I name the item it properly adds the ta
![2022-01-05_21 28 55](https://user-images.githubusercontent.com/97121216/148284680-bce6a70c-6c90-4d95-b190-3e2d95676a0f.png)
g

**Comment by CrimsonFluff** [comment]
try this
https://1drv.ms/u/s!ArSGAcC04KWsyxRkhbCeClgk53nC?e=b7ePwd

**Comment by Sakens** [comment]
Okay forget what i said. If I add the enchantment it doesnt work but once i rename the item it properly adds it.
[latest.log](https://github.com/CrimsonFluff/Unbreakables/files/7817651/latest.log)

**Comment by CrimsonFluff** [comment]
even with the latest version I posted a few minutes ago?

**Comment by Sakens** [comment]
yes i tried it

**Comment by CrimsonFluff** [comment]
weird, cos I removed the empty check so it should have worked

**Comment by Sakens** [comment]
Uhhh can i ask you something. Can you Shift click your tools in the anvil? because if i do that it doesnt work but if i manually click it in it works

**Comment by Sakens** [comment]
Okay i get it now. Shift click the rightmost slot in the anvil this seems to cause it if you pick it up normally it works just fine

**Comment by CrimsonFluff** [comment]
So - don't shift click the item out of the Anvil - it wont work !

damn that took some searching for... Well Done !!!

I'll add a note to the curse forge page to tell people

I guess I should report that to Forge...

**Comment by Sakens** [comment]
Im gonna close that issue now alright?

**Comment by CrimsonFluff** [comment]
go for it

**Comment by CrimsonFluff** [comment]
this seems to be same as Forge Issue 8487
