### ISSUE TITLE
Tetra support

### ISSUE THREAD

**Issue by p3lim** [CrimsonFluff/Unbreakables#2]
**Basic Mod Information**
Forge Version: 39.0.9
Mod Version: 1.18.1-1.0.0

**Describe the bug**
What is the bug? What did you do to make it happen? is it repeatable? 

When applied to [Tetra](https://www.curseforge.com/minecraft/mc-mods/tetra) tools it does nothing.

**Comment by CrimsonFluff** [comment]
thats because its for vanilla tools, like the description says
